parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"hHyE":[function(require,module,exports) {
"use strict";function o(t){return(o="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(o){return typeof o}:function(o){return o&&"function"==typeof Symbol&&o.constructor===Symbol&&o!==Symbol.prototype?"symbol":typeof o})(t)}exports.__esModule=!0,exports.isFql=function(t){return"object"===o(t)&&"__"===Object.keys(t)[0].slice(0,2)};
},{}],"JKu9":[function(require,module,exports) {
"use strict";exports.__esModule=!0,exports.singleFql=function(e,r,t,n){var o="call"===e?r:r.args,s="call"===e?Object.assign({},o,{fns:n}):o.concat([n]);if(!n)throw new Error("No 'fns' argument has been provided");if(!n[t]&&"ac"===t)throw new Error("There is a function in your query that has not been passed to the fql interpreter");if(!n[t]&&"ac"!==t)throw new Error("The '"+t+"' function exists in your query, but has not been passed to the fql interpreter");return n[t][e](null,s)};
},{}],"xh4o":[function(require,module,exports) {
"use strict";function e(t){return(e="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(t)}exports.__esModule=!0;var t=require("./single-fql");exports.fqlify=function(r,o){var c=Object.keys(o)[0].replace("__",""),n=Object.values(o)[0],y="object"===e(n)&&"args"===Object.keys(n)[0]?"apply":"call";return"object"===e(n)&&"curry"===Object.keys(n)[0]?n.curry.reduce(function(e,t){var r;return exports.fqlify({ac:e},((r={}).__ac=t,r))},r[c]):t.singleFql(y,n,c,r)};
},{"./single-fql":"JKu9"}],"jcHJ":[function(require,module,exports) {
"use strict";function o(e){return(o="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(o){return typeof o}:function(o){return o&&"function"==typeof Symbol&&o.constructor===Symbol&&o!==Symbol.prototype?"symbol":typeof o})(e)}exports.__esModule=!0;var e=require("../../index");exports.chain=function(t){var p=t.chain,l=t.fns;return p.slice(1).reduce(function(e,t){var p="object"===o(t)?"complex":"simple",l="complex"===p?Object.keys(t)[0]:t,r="complex"===p?"method":"simple"===p&&"function"==typeof e[t]?"method":"prop",c="complex"===p&&"method"===r&&t[l].args?"apply":"complex"===p&&"method"===r?"call":void 0,n="apply"===c?t[l].args:"call"===c?t[l]:void 0;return"simple"===p&&"prop"===r?e[t]:"simple"===p&&"method"===r?e[t]():"complex"===p&&"apply"===c?e[l].apply(e,n):"complex"===p&&"call"===c?e[l](n):void 0},e.fql(l,p[0]))};
},{"../../index":"7QCb"}],"7QCb":[function(require,module,exports) {
"use strict";exports.__esModule=!0;var r=require("./fns/is-fql"),e=require("./fns/fqlify"),i=require("./fns/aux/chain");exports.fql=function(i,n){try{return r.isFql(n)?e.fqlify(i,n):n}catch(s){console.log("Error in fql mapping"),console.error(s)}},exports.chain=i.chain;
},{"./fns/is-fql":"hHyE","./fns/fqlify":"xh4o","./fns/aux/chain":"jcHJ"}]},{},["7QCb"], null)
//# sourceMappingURL=/index.js.map